<div class="newsletter-group">
	<div class="container">
		<div class="container-inner">
			<div class="col1">
				<?php echo $this->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('subscribe.phtml')->toHtml();?>
			</div>
			<div class="col2">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social')->toHtml();?>
			</div>
		</div>
	</div>
</div>
