<div class="slider-group">
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-sm-12 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('bannerslider.phtml')->toHtml();?>
			</div>
			<div class="col2 col-md-3 col-sm-12 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static_top_lavante1')->toHtml();?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
require(["jquery"], function($){
	
   $("#static_top_lavante1").owlCarousel({ 
		autoPlay : false,
		slideSpeed : 1000,
		navigation : true,
		stopOnHover : true,
		pagination : false,
		items : 2,
		itemsDesktop : [1199,2],
		itemsDesktopSmall : [992,2],
		itemsTablet: [767,2],
		itemsMobile : [479,1],
		addClassActive : true,
		scrollPerPage:false
   });
   
});
</script>  