<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('static_bottom_lavante1')->toHtml();?>
<script type="text/javascript">
require(["jquery"], function($){
	
   $("#static_bottom_lavante1").owlCarousel({ 
		autoPlay : false,
		slideSpeed : 1000,
		navigation : true,
		stopOnHover : true,
		pagination : false,
		items : 2,
		itemsDesktop : [1199,2],
		itemsDesktopSmall : [991,2],
		itemsTablet: [767,1],
		itemsMobile : [479,1],
		addClassActive : true,
		scrollPerPage:false
   });
   
});
</script>  